steps:
  # Step to build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/pocketbase-deployment/flask-app', '.']

  # Step to push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/pocketbase-deployment /flask-app']

  # Step to deploy the Docker image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'flask-app',
        '--image',
        'gcr.io/pocketbase-deployment/flask-app',
        '--platform',
        'managed',
        '--region',
        'asia-east1',
        '--allow-unauthenticated',
      ]

images:
  - 'gcr.io/pocketbase-deployment/flask-app'
