version: '3'

services:
  web:
    build: .
    ports:
      - '80:80' # Map port 80 on the host to port 80 in the container
    environment:
      - FLASK_ENV=production # Set Flask environment to production
    volumes:
      - .:/app
    command: gunicorn --bind 0.0.0.0:80 app:app # Run Gunicorn on port 80

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80' # Expose NGINX on port 80
    depends_on:
      - web
