version: '3'

services:
  web:
    build: .
    ports:
      - '80:5000' # Map port 80 on the host to port 5000 in the container
    environment:
      - FLASK_ENV=production
    volumes:
      - .:/app
    command: bash -c "if [ ${FLASK_ENV} = 'development' ]; then flask run --host=0.0.0.0 --port=5000; else service nginx start && gunicorn --bind 0.0.0.0:5000 app:app; fi"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80' # Expose NGINX on port 80 on the host
    depends_on:
      - web
